### ISSUE TITLE
Is there a guide on how to clone this repo and build the exes?

### ISSUE THREAD

**Issue by cc-leon** [Might-Magic-Heroes-5-5/MMH55#40]
Hi，dredknight!

I am a fellow HoMM5 player and a hobby programmer from a faraway land. I was fascinated by the inner workings of 5.5. May I know if you have any documentation of setting up the system and tools that I can follow and build? I may consider helping the contribution if I could figure out how it works and it is not beyond my current knowledge boundary.

Thanks!
 \- Leon

**Comment by dredknight** [comment]
Hey @cc-leon,

Great to hear you want to get involved!
This repo serves as a storage space for all the patches and tools we've made and used to build MMH55.
Unfortunately we dont have the raw code for the game and the only changes we do to EXE are through assembly hacking.
I suggest to join our discord channel and send me a PM as it is more convenient to talk there.

Cheers!
