### ISSUE TITLE
Empower Spells bonus damage to scale with hero level

### ISSUE THREAD

**Issue by dredknight** [Might-Magic-Heroes-5-5/MMH55#98]
Changes Empowered spell bonus damage formula from (base_damage to dmg_per_level*Hero_level)*100%

https://github.com/Might-Magic-Heroes-5-5/MMH55/blob/master/assembly/patches/MMH55%20production%20patches/for%20stripped%20exe/empowered_damage_formula.yml

**Comment by AStaroverA** [comment]
How can I change this formula myself?

**Comment by dredknight** [comment]
> How can I change this formula myself?

Install MMH55 and go to Data/MMH55-Stats.pak and in the file inside change EmpoweredSpellsDamage_base value to one you wish
